package com.idp.template.generator;

import com.idp.template.dto.CreateTemplateRequest;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@Slf4j
@Component
public class SpringBootGenerator
        implements ProjectGenerator {

    @Override
    public void generate(
            CreateTemplateRequest request
    ) {

        try {

            Path projectRoot =
                    Path.of(
                            "generated",
                            request.serviceName()
                    );

            Files.createDirectories(projectRoot);

            String packagePath =
                    request.packageName()
                            .replace(".", "/");

            Path javaPath =
                    projectRoot.resolve(
                            "src/main/java/" + packagePath
                    );

            Path controllerPath =
                    javaPath.resolve("controller");

            Path servicePath =
                    javaPath.resolve("service");

            Path entityPath =
                    javaPath.resolve("entity");

            Path repositoryPath =
                    javaPath.resolve("repository");

            Path dtoPath =
                    javaPath.resolve("dto");

            Path resourcesPath =
                    projectRoot.resolve(
                            "src/main/resources"
                    );
            Path k8sPath =
                    projectRoot.resolve("k8s");

            Path githubWorkflowPath =
                    projectRoot.resolve(
                            ".github/workflows"
                    );

            Files.createDirectories(javaPath);
            Files.createDirectories(controllerPath);
            Files.createDirectories(servicePath);
            Files.createDirectories(entityPath);
            Files.createDirectories(repositoryPath);
            Files.createDirectories(dtoPath);
            Files.createDirectories(resourcesPath);
            Files.createDirectories(k8sPath);
            Files.createDirectories(githubWorkflowPath);

            // README

            Files.writeString(
                    projectRoot.resolve("README.md"),
                    """
                    # %s

                    Generated by IDP Template Service.
                    """
                            .formatted(
                                    request.serviceName()
                            )
            );

            // Dockerfile

            Files.writeString(
                    projectRoot.resolve("Dockerfile"),
                    """
                    FROM eclipse-temurin:21-jdk

                    WORKDIR /app

                    COPY build/libs/*.jar app.jar

                    ENTRYPOINT ["java","-jar","app.jar"]
                    """
            );

            // build.gradle

            Files.writeString(
                    projectRoot.resolve("build.gradle"),
                    """
                    plugins {
                        id 'java'
                        id 'org.springframework.boot' version '3.5.3'
                        id 'io.spring.dependency-management' version '1.1.7'
                    }

                    group = '%s'
                    version = '0.0.1-SNAPSHOT'

                    java {
                        toolchain {
                            languageVersion = JavaLanguageVersion.of(21)
                        }
                    }

                    repositories {
                        mavenCentral()
                    }

                    dependencies {

                        implementation 'org.springframework.boot:spring-boot-starter-web'
                            
                        implementation 'org.springframework.boot:spring-boot-starter-validation'
                            
                        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
                            
                        implementation 'org.springframework.boot:spring-boot-starter-actuator'
                        
                        runtimeOnly 'org.postgresql:postgresql'
                            
                        compileOnly 'org.projectlombok:lombok'
                        annotationProcessor 'org.projectlombok:lombok'
                            
                        testImplementation 'org.springframework.boot:spring-boot-starter-test'
                    }

                    tasks.named('test') {
                        useJUnitPlatform()
                    }
                    """
                            .formatted(
                                    request.groupId()
                            )
            );

            // settings.gradle

            Files.writeString(
                    projectRoot.resolve(
                            "settings.gradle"
                    ),
                    """
                    rootProject.name='%s'
                    """
                            .formatted(
                                    request.artifactId()
                            )
            );

            // Application.java

            Files.writeString(
                    javaPath.resolve(
                            "Application.java"
                    ),
                    """
                    package %s;

                    import org.springframework.boot.SpringApplication;
                    import org.springframework.boot.autoconfigure.SpringBootApplication;

                    @SpringBootApplication
                    public class Application {

                        public static void main(String[] args) {

                            SpringApplication.run(
                                    Application.class,
                                    args
                            );
                        }
                    }
                    """
                            .formatted(
                                    request.packageName()
                            )
            );

            // HealthController.java

            Files.writeString(
                    controllerPath.resolve(
                            "HealthController.java"
                    ),
                    """
                    package %s.controller;

                    import org.springframework.web.bind.annotation.GetMapping;
                    import org.springframework.web.bind.annotation.RestController;

                    @RestController
                    public class HealthController {

                        @GetMapping("/health")
                        public String health() {

                            return "UP";
                        }
                    }
                    """
                            .formatted(
                                    request.packageName()
                            )
            );

            // HealthService.java

            Files.writeString(
                    servicePath.resolve(
                            "HealthService.java"
                    ),
                    """
                    package %s.service;

                    import org.springframework.stereotype.Service;

                    @Service
                    public class HealthService {

                        public String health() {

                            return "UP";
                        }
                    }
                    """
                            .formatted(
                                    request.packageName()
                            )
            );

            // application.properties

            Files.writeString(
                    resourcesPath.resolve(
                            "application.properties"
                    ),
                    """
                    spring.application.name=%s
                    
                    server.port=8080
                    
                    spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
                    spring.datasource.username=postgres
                    spring.datasource.password=postgres
                    
                    spring.jpa.hibernate.ddl-auto=update
                    spring.jpa.show-sql=true
                    
                    management.endpoints.web.exposure.include=*
                    management.endpoint.health.show-details=always
                    """
                            .formatted(
                                    request.serviceName()
                            )
            );


            // Customer.java

            Files.writeString(
                    entityPath.resolve(
                            "Customer.java"
                    ),
                    """
                    package %s.entity;
            
                    import jakarta.persistence.*;
                    import lombok.*;
            
                    @Entity
                    @Getter
                    @Setter
                    @NoArgsConstructor
                    @AllArgsConstructor
                    @Builder
                    public class Customer {
            
                        @Id
                        @GeneratedValue(
                                strategy =
                                GenerationType.IDENTITY
                        )
                        private Long id;
            
                        private String name;
                    }
                    """
                            .formatted(
                                    request.packageName()
                            )
            );

// CustomerRepository.java

            Files.writeString(
                    repositoryPath.resolve(
                            "CustomerRepository.java"
                    ),
                    """
                    package %s.repository;
            
                    import %s.entity.Customer;
            
                    import org.springframework.data.jpa.repository.JpaRepository;
            
                    public interface CustomerRepository
                            extends JpaRepository<
                                    Customer,
                                    Long
                            > {
                    }
                    """
                            .formatted(
                                    request.packageName(),
                                    request.packageName()
                            )
            );

// CustomerRequest.java

            Files.writeString(
                    dtoPath.resolve(
                            "CustomerRequest.java"
                    ),
                    """
                    package %s.dto;
            
                    public record CustomerRequest(
            
                            String name
            
                    ) {
                    }
                    """
                            .formatted(
                                    request.packageName()
                            )
            );

// CustomerResponse.java

            Files.writeString(
                    servicePath.resolve(
                            "CustomerService.java"
                    ),
                    """
                    package %s.service;
            
                    import %s.dto.CustomerRequest;
                    import %s.dto.CustomerResponse;
                    import %s.entity.Customer;
                    import %s.repository.CustomerRepository;
            
                    import lombok.RequiredArgsConstructor;
                    import org.springframework.stereotype.Service;
            
                    import java.util.List;
            
                    @Service
                    @RequiredArgsConstructor
                    public class CustomerService {
            
                        private final CustomerRepository repository;
            
                        public CustomerResponse create(
                                CustomerRequest request
                        ) {
            
                            Customer customer =
                                    repository.save(
                                            Customer.builder()
                                                    .name(request.name())
                                                    .build()
                                    );
            
                            return new CustomerResponse(
                                    customer.getId(),
                                    customer.getName()
                            );
                        }
            
                        public List<Customer> findAll() {
            
                            return repository.findAll();
                        }
                    }
                    """
                            .formatted(
                                    request.packageName(),
                                    request.packageName(),
                                    request.packageName(),
                                    request.packageName(),
                                    request.packageName()
                            )
            );

            Files.writeString(
                    controllerPath.resolve(
                            "CustomerController.java"
                    ),
                    """
                    package %s.controller;
            
                    import %s.dto.CustomerRequest;
                    import %s.dto.CustomerResponse;
                    import %s.entity.Customer;
                    import %s.service.CustomerService;
            
                    import lombok.RequiredArgsConstructor;
            
                    import org.springframework.web.bind.annotation.*;
            
                    import java.util.List;
            
                    @RestController
                    @RequestMapping("/customers")
                    @RequiredArgsConstructor
                    public class CustomerController {
            
                        private final CustomerService service;
            
                        @PostMapping
                        public CustomerResponse create(
                                @RequestBody CustomerRequest request
                        ) {
            
                            return service.create(request);
                        }
            
                        @GetMapping
                        public List<Customer> findAll() {
            
                            return service.findAll();
                        }
                    }
                    """
                            .formatted(
                                    request.packageName(),
                                    request.packageName(),
                                    request.packageName(),
                                    request.packageName(),
                                    request.packageName()
                            )
            );



            Files.writeString(
                    dtoPath.resolve(
                            "CustomerResponse.java"
                    ),
                    """
                    package %s.dto;
            
                    public record CustomerResponse(
            
                            Long id,
            
                            String name
            
                    ) {
                    }
                    """
                            .formatted(
                                    request.packageName()
                            )
            );

            Files.writeString(
                    k8sPath.resolve(
                            "deployment.yaml"
                    ),
                    """
                    apiVersion: apps/v1
                    kind: Deployment
            
                    metadata:
                      name: %s
            
                    spec:
                      replicas: 1
            
                      selector:
                        matchLabels:
                          app: %s
            
                      template:
                        metadata:
                          labels:
                            app: %s
            
                        spec:
                          containers:
                            - name: %s
                              image: %s:latest
            
                              ports:
                                - containerPort: 8080
                    """
                            .formatted(
                                    request.serviceName(),
                                    request.serviceName(),
                                    request.serviceName(),
                                    request.serviceName(),
                                    request.serviceName()
                            )
            );

            Files.writeString(
                    k8sPath.resolve(
                            "service.yaml"
                    ),
                    """
                    apiVersion: v1
                    kind: Service
            
                    metadata:
                      name: %s
            
                    spec:
                      selector:
                        app: %s
            
                      ports:
                        - port: 80
                          targetPort: 8080
            
                      type: ClusterIP
                    """
                            .formatted(
                                    request.serviceName(),
                                    request.serviceName()
                            )
            );

            Files.writeString(
                    githubWorkflowPath.resolve(
                            "build.yml"
                    ),
                    """
                    name: Build
            
                    on:
                      push:
                        branches:
                          - main
            
                    jobs:
            
                      build:
            
                        runs-on: ubuntu-latest
            
                        steps:
            
                          - uses: actions/checkout@v4
            
                          - uses: actions/setup-java@v4
                            with:
                              distribution: temurin
                              java-version: '21'
            
                          - name: Build
                            run: ./gradlew build
                    """
            );
            log.info(
                    "Generated project at {}",
                    projectRoot.toAbsolutePath()
            );

        } catch (IOException e) {

            throw new RuntimeException(
                    "Project generation failed",
                    e
            );
        }
    }
}