spring.application.name=template-service

server.port=8088

github.service.url=http://github-service:8087

catalog.service.url=http://catalog-service:8082

github.token=${GITHUB_TOKEN}

github.owner=${GITHUB_OWNER}

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

management.health.defaults.enabled=true
